### ISSUE TITLE
[BUG] pod_delete test outputs API text during `cert` run

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1974]
**Describe the bug**
There seems to be API output when running the `cert` option that should be suppressed information as it breaks the PASS/FAIL/SKIP output when running the testsuite

**To Reproduce**
Run `cert` against your CNF, in this example it was the sample-coredns-cnf/ configuration sample.

**Expected behavior**
There should be no template or config API output when running the certification as it breaks the formatting of the output for tests.

**Screenshots**
```
Reliability, Resilience, and Availability Tests
✔️  ✨PASSED: pod_network_latency chaos test passed 🗡️💀♻
✔️  ✨PASSED: pod_network_corruption chaos test passed 🗡️💀♻
✔️  PASSED: disk_fill chaos test passed 🗡️💀♻
Running for: {"app.kubernetes.io/instance" => "coredns", "app.kubernetes.io/name" => "coredns", "k8s-app" => "coredns"}
Spec Hash: 
template: apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: coredns-coredns-26
  namespace: cnfspace
spec:
  engineState: 'active'
  appinfo:
    appns: 'cnfspace'
    applabel: 'app.kubernetes.io/instance=coredns'
    appkind: 'deployment'
  chaosServiceAccount: pod-delete-sa
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # specify the fill percentage according to the disk pressure required
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            - name: CHAOS_INTERVAL
              value: '10'

            - name: TARGET_PODS
              value: ''
            - name: FORCE
              value: 'false'
✔️  PASSED: pod_delete chaos test passed 🗡️💀♻
```
<img width="1064" alt="Screenshot 2024-04-15 at 12 50 18 PM" src="https://github.com/cnti-testcatalog/testsuite/assets/14348948/8832f6bd-31fa-4b41-a770-239f4ab5b444">
